services:
  berlinweb:
    build:
      context: .
      dockerfile: Dockerfile_web
      args:
        - WEBPORT=${WEB_PORT}  # Aqu√≠ passes el valor a l'ARG del Dockerfile
        - HUBPORT=${HUB_PORT}
    ports:
      - 8443:${WEB_PORT}
      - 8080:${HUB_PORT}
  berlinpty:
    build:
      context: .
      dockerfile: Dockerfile_pty
