[package]
name = "berlinproto"
version = "0.1.0"
edition = "2024"

[dependencies]
totp-rs = { version = "5.5", features = ["qr"] }
rand ={ version = "0.9"}
serde={version="1.0", features = ["derive"]}
serde_json={version = "1.0"}