[package]
name = "berlinpty"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
portable-pty = "0.9"
berlinproto = { path = "../berlinproto" }
serde_json={version = "1.0"}
hostname = "0.4"